#!/usr/bin/env bash
#
# demo3_run.sh — RUNS INSIDE the ws container. Swaps the RMW for the SAME node binaries
# (demo_basic talker + demo_qos qos_sub counter), proves data flows under all three RMWs,
# then shows DDS<->DDS wire interop, DDS<->Zenoh NON-interop, and ROS_DOMAIN_ID isolation.
# Writes real results to docs/05-rmw.md. No `set -u` (ROS setup.bash isn't -u safe).
set -o pipefail
source /opt/ros/jazzy/setup.bash
source /repo/ws/install/setup.bash
source /repo/scripts/lib.sh

IMG=/repo/docs/img
DOC=/repo/docs/05-rmw.md
mkdir -p "$IMG" "$(dirname "$DOC")"
DOM=42
: > "$IMG/demo3_active_rmw.txt"

recv() { grep -oE 'RECEIVED:[0-9]+' <<<"$1" | grep -oE '[0-9]+' | tail -1; }

ZENOH_PID=""
start_zenoh_router() {
  log "Starting rmw_zenohd router (rmw_zenoh disables multicast scouting by default)..."
  RMW_IMPLEMENTATION=rmw_zenoh_cpp ROS_DOMAIN_ID=$DOM \
    ros2 run rmw_zenoh_cpp rmw_zenohd > /tmp/zenohd.log 2>&1 &
  ZENOH_PID=$!
  sleep 4
}
stop_all() {
  [ -n "$ZENOH_PID" ] && kill "$ZENOH_PID" 2>/dev/null
  pkill -f 'demo_basic talker' 2>/dev/null
  pkill -f 'demo_qos qos_sub'  2>/dev/null
  wait 2>/dev/null; true
}
trap stop_all EXIT

# flow <pub_rmw> <pub_dom> <sub_rmw> <sub_dom> <topic> -> echoes the sub's received count
flow() {
  local prmw=$1 pdom=$2 srmw=$3 sdom=$4 topic=$5
  RMW_IMPLEMENTATION=$prmw ROS_DOMAIN_ID=$pdom \
    ros2 run demo_basic talker --ros-args -r chatter:="$topic" > /tmp/flow_pub.log 2>&1 &
  local pub=$!
  sleep 2
  local out
  out=$(RMW_IMPLEMENTATION=$srmw ROS_DOMAIN_ID=$sdom timeout 12 \
    ros2 run demo_qos qos_sub --ros-args -p topic:="$topic" -p reliability:=reliable -p run_seconds:=4 2>&1)
  kill "$pub" 2>/dev/null; wait "$pub" 2>/dev/null
  recv "$out"
}

report_rmw() {
  ros2 daemon stop >/dev/null 2>&1   # the ros2 daemon caches the RMW from first launch
  RMW_IMPLEMENTATION=$1 ros2 doctor --report 2>/dev/null \
    | awk 'tolower($0) ~ /middleware name/ {print "'"$1"'\t" $0}'
}

declare -A RES
log "=== Part A: same-RMW data flow + active-RMW report, all three RMWs ==="
for rmw in rmw_fastrtps_cpp rmw_cyclonedds_cpp rmw_zenoh_cpp; do
  [ "$rmw" = "rmw_zenoh_cpp" ] && [ -z "$ZENOH_PID" ] && start_zenoh_router
  report_rmw "$rmw" | tee -a "$IMG/demo3_active_rmw.txt"
  RES[$rmw]=$(flow "$rmw" $DOM "$rmw" $DOM "t_${rmw}")
  RES[$rmw]=${RES[$rmw]:-NA}
  log "  $rmw flow received: ${RES[$rmw]}"
done

log "=== Part B: cross-RMW interop ==="
IOP_DDS=$(flow rmw_fastrtps_cpp $DOM rmw_cyclonedds_cpp $DOM t_dds_interop); IOP_DDS=${IOP_DDS:-NA}
log "  Fast DDS talker -> Cyclone DDS listener: $IOP_DDS  (expect >=1; shared DDSI-RTPS wire)"
IOP_ZEN=$(flow rmw_fastrtps_cpp $DOM rmw_zenoh_cpp $DOM t_dds_zenoh); IOP_ZEN=${IOP_ZEN:-NA}
log "  Fast DDS talker -> Zenoh listener: $IOP_ZEN  (expect 0; Zenoh wire != DDSI-RTPS)"

log "=== Part C: ROS_DOMAIN_ID isolation (same RMW) ==="
ISO=$(flow rmw_fastrtps_cpp 42 rmw_fastrtps_cpp 99 t_domain); ISO=${ISO:-NA}
log "  domain 42 talker -> domain 99 listener: $ISO  (expect 0)"

stop_all; trap - EXIT

log "Writing real results to ${DOC} ..."
cat > "$DOC" <<EOF
# RMW / middleware swap (Demo 3)

> **Auto-generated by \`scripts/demo3_run.sh\` from a REAL run.** The *same* node binaries
> (\`demo_basic talker\` + a counting subscriber) run over three middlewares by flipping one
> env var, \`RMW_IMPLEMENTATION\`. The RMW is a swappable transport/HAL behind the stable
> \`rcl\`/\`rmw\` API — like retargeting firmware from UART to SPI to CAN by swapping the HAL.

## Same-RMW data flow (4 s window, depth 10, domain ${DOM})

| RMW_IMPLEMENTATION | Msgs received | Notes |
|---|---|---|
| rmw_fastrtps_cpp (Fast DDS, default) | ${RES[rmw_fastrtps_cpp]} | Tier 1 |
| rmw_cyclonedds_cpp (Cyclone DDS) | ${RES[rmw_cyclonedds_cpp]} | Tier 1 |
| rmw_zenoh_cpp (Zenoh) | ${RES[rmw_zenoh_cpp]} | available add-on on Jazzy (Tier 1 only from Kilted); needs the \`rmw_zenohd\` router |

Active-RMW report (\`ros2 doctor\`) per leg is captured in \`docs/img/demo3_active_rmw.txt\`.
The \`ros2 daemon\` caches the RMW from first launch, so each swap runs \`ros2 daemon stop\` first.

## Cross-RMW interop

| Publisher RMW | Subscriber RMW | Msgs received | Result |
|---|---|---|---|
| Fast DDS | Cyclone DDS | ${IOP_DDS} | ✅ **interoperate** — both speak the OMG DDSI-RTPS wire protocol |
| Fast DDS | Zenoh | ${IOP_ZEN} | ❌ **no data** — Zenoh uses its own wire protocol, not DDSI-RTPS |

Caveats stated honestly: DDS↔DDS interop holds for **topics** with matching QoS/types;
cross-vendor **services/actions are not guaranteed**, and ROS 2 still recommends one RMW
system-wide. DDS↔Zenoh needs a **bridge** (\`zenoh-bridge-ros2dds\`); they do not discover
each other natively.

## ROS_DOMAIN_ID isolation (same RMW)

| Talker domain | Listener domain | Msgs received | Result |
|---|---|---|---|
| 42 | 99 | ${ISO} | ❌ isolated — different domains never discover each other |

\`ROS_DOMAIN_ID\` is the canonical lightweight isolation knob and works identically under
host networking — it is how we keep concurrent demos from cross-talking, not container walls.
EOF

log "=== acceptance ==="
for rmw in rmw_fastrtps_cpp rmw_cyclonedds_cpp rmw_zenoh_cpp; do
  { [ "${RES[$rmw]}" != "NA" ] && [ "${RES[$rmw]}" -ge 1 ]; } \
    && ok "$rmw data flows (${RES[$rmw]} msgs)" || die "$rmw expected >=1, got ${RES[$rmw]}"
  grep -qF "$rmw" "$IMG/demo3_active_rmw.txt" && ok "active-RMW report names $rmw" \
    || die "active-RMW report missing $rmw"
done
{ [ "$IOP_DDS" != "NA" ] && [ "$IOP_DDS" -ge 1 ]; } && ok "Fast DDS<->Cyclone interop ($IOP_DDS msgs)" || die "DDS interop expected >=1, got $IOP_DDS"
[ "$IOP_ZEN" = "0" ] && ok "Fast DDS<->Zenoh NON-interop (0 msgs)" || die "DDS<->Zenoh expected 0, got $IOP_ZEN"
[ "$ISO" = "0" ]     && ok "domain isolation (0 msgs across domains)" || die "domain isolation expected 0, got $ISO"
ok "Demo 3 acceptance PASSED"
