#!/usr/bin/env bash
#
# qos_run.sh — RUNS INSIDE the ws container. Runs the QoS compatibility matrix for real,
# writes a REAL results table to docs/03-qos.md, captures live `ros2 topic info -v`, and
# asserts acceptance. No `set -u` (ROS setup.bash isn't -u safe).
set -o pipefail
source /opt/ros/jazzy/setup.bash
source /repo/ws/install/setup.bash
source /repo/scripts/lib.sh

DOC=/repo/docs/03-qos.md
IMG=/repo/docs/img
mkdir -p "$IMG" "$(dirname "$DOC")"

# run_pair <topic> <pub_rel> <pub_dur> <sub_rel> <sub_dur> <warmup_s> <run_s>
# Echoes the subscriber's captured output (incl. its "RECEIVED:<n> FIRST:<data>" line).
run_pair() {
  local topic=$1 prel=$2 pdur=$3 srel=$4 sdur=$5 warm=${6:-1} runs=${7:-4}
  ros2 run demo_qos qos_pub --ros-args \
    -p topic:="$topic" -p reliability:="$prel" -p durability:="$pdur" -p depth:=10 \
    > "/tmp/pub_${topic}.log" 2>&1 &
  local pub=$!
  sleep "$warm"
  local out
  out=$(timeout $((runs + 8)) ros2 run demo_qos qos_sub --ros-args \
    -p topic:="$topic" -p reliability:="$srel" -p durability:="$sdur" -p depth:=10 \
    -p run_seconds:="$runs" 2>&1)
  kill "$pub" 2>/dev/null; wait "$pub" 2>/dev/null
  echo "$out"
}
recv()     { grep -oE 'RECEIVED:[0-9]+'        <<<"$1" | grep -oE '[0-9]+'  | tail -1; }
firstidx() { grep -oE 'FIRST:qos msg [0-9]+'   <<<"$1" | grep -oE '[0-9]+$' | tail -1; }
warned()   { grep -qiE 'incompatible|requested|QOS'  <<<"$1" && echo yes || echo no; }

log "Case 1: best_effort pub -> reliable sub  (RxO INCOMPATIBLE; expect 0)"
O1=$(run_pair qos_c1 best_effort volatile reliable volatile 1 4); R1=$(recv "$O1"); W1=$(warned "$O1")
log "Case 2: reliable pub -> best_effort sub  (compatible; expect >=1)"
O2=$(run_pair qos_c2 reliable volatile best_effort volatile 1 4); R2=$(recv "$O2")
log "Case 3: volatile pub -> transient_local sub  (durability INCOMPATIBLE; expect 0)"
O3=$(run_pair qos_c3 reliable volatile reliable transient_local 1 4); R3=$(recv "$O3"); W3=$(warned "$O3")

log "Case 4: late-joiner — transient_local pub stays up; sub joins after ~15 msgs"
ros2 run demo_qos qos_pub --ros-args -p topic:=qos_late -p reliability:=reliable \
  -p durability:=transient_local -p depth:=10 > /tmp/pub_late.log 2>&1 &
PUB_LATE=$!
sleep 3
OTL=$(timeout 10 ros2 run demo_qos qos_sub --ros-args -p topic:=qos_late -p reliability:=reliable \
  -p durability:=transient_local -p depth:=10 -p run_seconds:=2 2>&1)
OVOL=$(timeout 10 ros2 run demo_qos qos_sub --ros-args -p topic:=qos_late -p reliability:=reliable \
  -p durability:=volatile -p depth:=10 -p run_seconds:=2 2>&1)
kill "$PUB_LATE" 2>/dev/null; wait "$PUB_LATE" 2>/dev/null
RTL=$(recv "$OTL"); FTL=$(firstidx "$OTL")
RVOL=$(recv "$OVOL"); FVOL=$(firstidx "$OVOL")

log "Capturing live 'ros2 topic info -v' (per-endpoint QoS) on an incompatible pair..."
ros2 run demo_qos qos_pub --ros-args -p topic:=qos_info -p reliability:=best_effort \
  -p durability:=volatile -p depth:=5 > /tmp/pub_info.log 2>&1 &
PI=$!
ros2 run demo_qos qos_sub --ros-args -p topic:=qos_info -p reliability:=reliable \
  -p durability:=volatile -p depth:=5 -p run_seconds:=30 > /tmp/sub_info.log 2>&1 &
SI=$!
sleep 3
ros2 topic info /qos_info -v > "$IMG/demo2_topic_info.txt" 2>&1 || true
kill "$PI" "$SI" 2>/dev/null; wait 2>/dev/null

# normalize empties so arithmetic/printing never breaks
R1=${R1:-NA}; R2=${R2:-NA}; R3=${R3:-NA}; RTL=${RTL:-NA}; RVOL=${RVOL:-NA}
FTL=${FTL:-NA}; FVOL=${FVOL:-NA}

log "Writing real results table to ${DOC} ..."
cat > "$DOC" <<EOF
# QoS compatibility (Demo 2)

> **Auto-generated by \`scripts/qos_run.sh\` from a REAL run — do not hand-edit the table.**
> Topic = \`std_msgs/String\`, publisher 5 Hz, subscriber window 4 s, depth 10.

## The rule (Request-vs-Offered, "RxO")

A **subscription requests** the *minimum* quality it will accept; a **publisher offers** the
*maximum* it provides. They connect only if **offered ≥ requested** for every policy — the
publisher side must be the *stronger* of the pair. It is an **AND** across policies: fixing
reliability while durability still mismatches still delivers **nothing**.

Only **reliability, durability, deadline, liveliness** participate in compatibility.
**History, Depth, and Lifespan do NOT** affect whether two endpoints connect.

## Results (real, this machine)

| # | Publisher offers | Subscriber requests | Msgs received | Compatible? |
|---|---|---|---|---|
| 1 | best_effort / volatile | reliable / volatile | **${R1}** | ❌ incompatible (offered < requested reliability) |
| 2 | reliable / volatile | best_effort / volatile | **${R2}** | ✅ compatible (offered > requested) |
| 3 | reliable / volatile | reliable / transient_local | **${R3}** | ❌ incompatible (volatile offered < transient_local requested) |

**Late-joiner (durability latching), both sides on \`/qos_late\`, publisher kept running:**

| Subscriber durability | Msgs in 2 s window | First message seen | Meaning |
|---|---|---|---|
| transient_local | ${RTL} | \`qos msg ${FTL}\` | gets **old/latched** samples sent before it joined |
| volatile | ${RVOL} | \`qos msg ${FVOL}\` | gets **new only**; \`${FVOL}\` ≫ \`${FTL}\` confirms latching needs transient_local on **both** sides |

The incompatible cases are **not silent**: the RMW logs an incompatible-QoS warning
(observed in case 1/3 output: \`$( [ "$W1" = yes ] || [ "$W3" = yes ] && echo "warning logged" || echo "see node logs")\`).
Per-endpoint QoS for an incompatible pair is captured in \`docs/img/demo2_topic_info.txt\`.
EOF

log "=== acceptance ==="
[ "$R1" = "0" ]                          && ok "case 1 best_effort->reliable = 0 (incompatible)"   || die "case 1 expected 0, got $R1"
{ [ "$R2" != "NA" ] && [ "$R2" -ge 1 ]; } && ok "case 2 reliable->best_effort >= 1 (got $R2)"        || die "case 2 expected >=1, got $R2"
[ "$R3" = "0" ]                          && ok "case 3 volatile->transient_local = 0 (incompatible)" || die "case 3 expected 0, got $R3"
{ [ "$RTL" != "NA" ] && [ "$RTL" -ge 1 ]; } && ok "case 4 late transient_local sub got old samples (got $RTL)" || die "case 4 expected >=1, got $RTL"
{ [ "$FTL" != "NA" ] && [ "$FVOL" != "NA" ] && [ "$FTL" -lt "$FVOL" ]; } \
  && ok "latching: transient_local first idx $FTL < volatile first idx $FVOL" \
  || die "latching not demonstrated (FTL=$FTL FVOL=$FVOL)"
test -s "$IMG/demo2_topic_info.txt"      && ok "captured topic info -v"                              || die "topic info -v not captured"
ok "Demo 2 acceptance PASSED"
